// Mocks generated by Mockito 5.4.6 from annotations
// in fathiyah_store/test/modules/pos/pos_view_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i14;
import 'dart:ui' as _i16;

import 'package:fathiyah_store/app/data/models/category_model.dart' as _i17;
import 'package:fathiyah_store/app/data/models/customer_model.dart' as _i13;
import 'package:fathiyah_store/app/data/models/product_model.dart' as _i12;
import 'package:fathiyah_store/app/data/models/sale_model.dart' as _i6;
import 'package:fathiyah_store/app/data/models/shift_model.dart' as _i18;
import 'package:fathiyah_store/app/data/models/user_model.dart' as _i19;
import 'package:fathiyah_store/app/data/services/auth_service.dart' as _i10;
import 'package:fathiyah_store/app/data/services/category_service.dart' as _i8;
import 'package:fathiyah_store/app/data/services/customer_service.dart' as _i9;
import 'package:fathiyah_store/app/data/services/product_service.dart' as _i7;
import 'package:fathiyah_store/app/data/services/sale_service.dart' as _i2;
import 'package:fathiyah_store/app/data/services/shift_service.dart' as _i3;
import 'package:fathiyah_store/app/modules/pos/controllers/pos_controller.dart'
    as _i11;
import 'package:flutter/material.dart' as _i5;
import 'package:get/get.dart' as _i4;
import 'package:get/get_state_manager/src/simple/list_notifier.dart' as _i15;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeSaleService_0 extends _i1.SmartFake implements _i2.SaleService {
  _FakeSaleService_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShiftService_1 extends _i1.SmartFake implements _i3.ShiftService {
  _FakeShiftService_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxString_2 extends _i1.SmartFake implements _i4.RxString {
  _FakeRxString_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTextEditingController_3 extends _i1.SmartFake
    implements _i5.TextEditingController {
  _FakeTextEditingController_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_4<T> extends _i1.SmartFake
    implements _i4.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxList_5<E> extends _i1.SmartFake implements _i4.RxList<E> {
  _FakeRxList_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRx_6<T> extends _i1.SmartFake implements _i4.Rx<T> {
  _FakeRx_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSaleModel_7 extends _i1.SmartFake implements _i6.SaleModel {
  _FakeSaleModel_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_8 extends _i1.SmartFake implements _i4.RxBool {
  _FakeRxBool_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductService_9 extends _i1.SmartFake
    implements _i7.ProductService {
  _FakeProductService_9(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCategoryService_10 extends _i1.SmartFake
    implements _i8.CategoryService {
  _FakeCategoryService_10(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeCustomerService_11 extends _i1.SmartFake
    implements _i9.CustomerService {
  _FakeCustomerService_11(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_12 extends _i1.SmartFake implements _i10.AuthService {
  _FakeAuthService_12(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [PosController].
///
/// See the documentation for Mockito's code generation for more information.
class MockPosController extends _i1.Mock implements _i11.PosController {
  MockPosController() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.SaleService get saleService =>
      (super.noSuchMethod(
            Invocation.getter(#saleService),
            returnValue: _FakeSaleService_0(
              this,
              Invocation.getter(#saleService),
            ),
          )
          as _i2.SaleService);

  @override
  _i3.ShiftService get shiftService =>
      (super.noSuchMethod(
            Invocation.getter(#shiftService),
            returnValue: _FakeShiftService_1(
              this,
              Invocation.getter(#shiftService),
            ),
          )
          as _i3.ShiftService);

  @override
  _i4.RxString get searchQuery =>
      (super.noSuchMethod(
            Invocation.getter(#searchQuery),
            returnValue: _FakeRxString_2(this, Invocation.getter(#searchQuery)),
          )
          as _i4.RxString);

  @override
  _i5.TextEditingController get paidAmountController =>
      (super.noSuchMethod(
            Invocation.getter(#paidAmountController),
            returnValue: _FakeTextEditingController_3(
              this,
              Invocation.getter(#paidAmountController),
            ),
          )
          as _i5.TextEditingController);

  @override
  _i4.RxString get paymentMethod =>
      (super.noSuchMethod(
            Invocation.getter(#paymentMethod),
            returnValue: _FakeRxString_2(
              this,
              Invocation.getter(#paymentMethod),
            ),
          )
          as _i4.RxString);

  @override
  List<_i12.ProductModel> get filteredProducts =>
      (super.noSuchMethod(
            Invocation.getter(#filteredProducts),
            returnValue: <_i12.ProductModel>[],
          )
          as List<_i12.ProductModel>);

  @override
  List<_i13.CustomerModel> get customers =>
      (super.noSuchMethod(
            Invocation.getter(#customers),
            returnValue: <_i13.CustomerModel>[],
          )
          as List<_i13.CustomerModel>);

  @override
  _i4.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  int get listeners =>
      (super.noSuchMethod(Invocation.getter(#listeners), returnValue: 0)
          as int);

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void selectCustomer(_i13.CustomerModel? customer) => super.noSuchMethod(
    Invocation.method(#selectCustomer, [customer]),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<void> processPayment() =>
      (super.noSuchMethod(
            Invocation.method(#processPayment, []),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void update([List<Object>? ids, bool? condition = true]) =>
      super.noSuchMethod(
        Invocation.method(#update, [ids, condition]),
        returnValueForMissingStub: null,
      );

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Disposer addListener(_i15.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListener, [listener]),
            returnValue: () {},
          )
          as _i15.Disposer);

  @override
  void removeListener(_i16.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void refresh() => super.noSuchMethod(
    Invocation.method(#refresh, []),
    returnValueForMissingStub: null,
  );

  @override
  void refreshGroup(Object? id) => super.noSuchMethod(
    Invocation.method(#refreshGroup, [id]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyChildrens() => super.noSuchMethod(
    Invocation.method(#notifyChildrens, []),
    returnValueForMissingStub: null,
  );

  @override
  void removeListenerId(Object? id, _i16.VoidCallback? listener) =>
      super.noSuchMethod(
        Invocation.method(#removeListenerId, [id, listener]),
        returnValueForMissingStub: null,
      );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i15.Disposer addListenerId(Object? key, _i15.GetStateUpdate? listener) =>
      (super.noSuchMethod(
            Invocation.method(#addListenerId, [key, listener]),
            returnValue: () {},
          )
          as _i15.Disposer);

  @override
  void disposeId(Object? id) => super.noSuchMethod(
    Invocation.method(#disposeId, [id]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SaleService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaleService extends _i1.Mock implements _i2.SaleService {
  MockSaleService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RxList<_i2.CartItem> get cartItems =>
      (super.noSuchMethod(
            Invocation.getter(#cartItems),
            returnValue: _FakeRxList_5<_i2.CartItem>(
              this,
              Invocation.getter(#cartItems),
            ),
          )
          as _i4.RxList<_i2.CartItem>);

  @override
  _i4.RxList<_i6.SaleModel> get sales =>
      (super.noSuchMethod(
            Invocation.getter(#sales),
            returnValue: _FakeRxList_5<_i6.SaleModel>(
              this,
              Invocation.getter(#sales),
            ),
          )
          as _i4.RxList<_i6.SaleModel>);

  @override
  _i4.Rx<_i13.CustomerModel?> get selectedCustomer =>
      (super.noSuchMethod(
            Invocation.getter(#selectedCustomer),
            returnValue: _FakeRx_6<_i13.CustomerModel?>(
              this,
              Invocation.getter(#selectedCustomer),
            ),
          )
          as _i4.Rx<_i13.CustomerModel?>);

  @override
  double get cartTotal =>
      (super.noSuchMethod(Invocation.getter(#cartTotal), returnValue: 0.0)
          as double);

  @override
  _i4.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i14.Future<_i2.SaleService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i14.Future<_i2.SaleService>.value(
              _FakeSaleService_0(this, Invocation.method(#init, [])),
            ),
          )
          as _i14.Future<_i2.SaleService>);

  @override
  void addToCart(_i12.ProductModel? product) => super.noSuchMethod(
    Invocation.method(#addToCart, [product]),
    returnValueForMissingStub: null,
  );

  @override
  void updateQuantity(String? productId, int? newQuantity) =>
      super.noSuchMethod(
        Invocation.method(#updateQuantity, [productId, newQuantity]),
        returnValueForMissingStub: null,
      );

  @override
  void setCustomer(_i13.CustomerModel? customer) => super.noSuchMethod(
    Invocation.method(#setCustomer, [customer]),
    returnValueForMissingStub: null,
  );

  @override
  void clearCart() => super.noSuchMethod(
    Invocation.method(#clearCart, []),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<_i6.SaleModel> processCheckout({
    required double? paidAmount,
    required String? paymentMethod,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#processCheckout, [], {
              #paidAmount: paidAmount,
              #paymentMethod: paymentMethod,
            }),
            returnValue: _i14.Future<_i6.SaleModel>.value(
              _FakeSaleModel_7(
                this,
                Invocation.method(#processCheckout, [], {
                  #paidAmount: paidAmount,
                  #paymentMethod: paymentMethod,
                }),
              ),
            ),
          )
          as _i14.Future<_i6.SaleModel>);

  @override
  Map<String, double> getDebtsByCustomer() =>
      (super.noSuchMethod(
            Invocation.method(#getDebtsByCustomer, []),
            returnValue: <String, double>{},
          )
          as Map<String, double>);

  @override
  List<_i6.SaleModel> getUnpaidSalesForCustomer(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#getUnpaidSalesForCustomer, [customerId]),
            returnValue: <_i6.SaleModel>[],
          )
          as List<_i6.SaleModel>);

  @override
  _i14.Future<void> payDebt(
    String? saleId,
    double? amount,
    String? paymentMethod,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#payDebt, [saleId, amount, paymentMethod]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ProductService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductService extends _i1.Mock implements _i7.ProductService {
  MockProductService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RxList<_i17.CategoryModel> get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: _FakeRxList_5<_i17.CategoryModel>(
              this,
              Invocation.getter(#categories),
            ),
          )
          as _i4.RxList<_i17.CategoryModel>);

  @override
  _i4.RxList<_i12.ProductModel> get products =>
      (super.noSuchMethod(
            Invocation.getter(#products),
            returnValue: _FakeRxList_5<_i12.ProductModel>(
              this,
              Invocation.getter(#products),
            ),
          )
          as _i4.RxList<_i12.ProductModel>);

  @override
  _i4.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_8(this, Invocation.getter(#isLoading)),
          )
          as _i4.RxBool);

  @override
  _i4.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i14.Future<_i7.ProductService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i14.Future<_i7.ProductService>.value(
              _FakeProductService_9(this, Invocation.method(#init, [])),
            ),
          )
          as _i14.Future<_i7.ProductService>);

  @override
  _i14.Future<void> addProduct(_i12.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> updateProduct(_i12.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CategoryService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCategoryService extends _i1.Mock implements _i8.CategoryService {
  MockCategoryService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RxList<_i17.CategoryModel> get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: _FakeRxList_5<_i17.CategoryModel>(
              this,
              Invocation.getter(#categories),
            ),
          )
          as _i4.RxList<_i17.CategoryModel>);

  @override
  _i4.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i14.Future<_i8.CategoryService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i14.Future<_i8.CategoryService>.value(
              _FakeCategoryService_10(this, Invocation.method(#init, [])),
            ),
          )
          as _i14.Future<_i8.CategoryService>);

  @override
  _i14.Future<void> addCategory(_i17.CategoryModel? category) =>
      (super.noSuchMethod(
            Invocation.method(#addCategory, [category]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> updateCategory(_i17.CategoryModel? category) =>
      (super.noSuchMethod(
            Invocation.method(#updateCategory, [category]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> deleteCategory(String? id, String? categoryName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCategory, [id, categoryName]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [CustomerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCustomerService extends _i1.Mock implements _i9.CustomerService {
  MockCustomerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.RxList<_i13.CustomerModel> get customers =>
      (super.noSuchMethod(
            Invocation.getter(#customers),
            returnValue: _FakeRxList_5<_i13.CustomerModel>(
              this,
              Invocation.getter(#customers),
            ),
          )
          as _i4.RxList<_i13.CustomerModel>);

  @override
  _i4.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i14.Future<_i9.CustomerService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i14.Future<_i9.CustomerService>.value(
              _FakeCustomerService_11(this, Invocation.method(#init, [])),
            ),
          )
          as _i14.Future<_i9.CustomerService>);

  @override
  _i14.Future<void> addCustomer(_i13.CustomerModel? customer) =>
      (super.noSuchMethod(
            Invocation.method(#addCustomer, [customer]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> updateCustomer(_i13.CustomerModel? updatedCustomer) =>
      (super.noSuchMethod(
            Invocation.method(#updateCustomer, [updatedCustomer]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> deleteCustomer(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteCustomer, [id]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> toggleVipStatus(String? customerId) =>
      (super.noSuchMethod(
            Invocation.method(#toggleVipStatus, [customerId]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ShiftService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShiftService extends _i1.Mock implements _i3.ShiftService {
  MockShiftService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Rx<_i18.ShiftModel?> get currentShift =>
      (super.noSuchMethod(
            Invocation.getter(#currentShift),
            returnValue: _FakeRx_6<_i18.ShiftModel?>(
              this,
              Invocation.getter(#currentShift),
            ),
          )
          as _i4.Rx<_i18.ShiftModel?>);

  @override
  _i4.RxList<_i18.ShiftModel> get shifts =>
      (super.noSuchMethod(
            Invocation.getter(#shifts),
            returnValue: _FakeRxList_5<_i18.ShiftModel>(
              this,
              Invocation.getter(#shifts),
            ),
          )
          as _i4.RxList<_i18.ShiftModel>);

  @override
  _i4.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i14.Future<_i3.ShiftService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i14.Future<_i3.ShiftService>.value(
              _FakeShiftService_1(this, Invocation.method(#init, [])),
            ),
          )
          as _i14.Future<_i3.ShiftService>);

  @override
  _i14.Future<void> openShift(double? startBalance) =>
      (super.noSuchMethod(
            Invocation.method(#openShift, [startBalance]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> closeShift(double? endBalance) =>
      (super.noSuchMethod(
            Invocation.method(#closeShift, [endBalance]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> recordCashSale(double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#recordCashSale, [amount]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> recordCashExpense(double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#recordCashExpense, [amount]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i10.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Rx<_i19.UserModel?> get currentUser =>
      (super.noSuchMethod(
            Invocation.getter(#currentUser),
            returnValue: _FakeRx_6<_i19.UserModel?>(
              this,
              Invocation.getter(#currentUser),
            ),
          )
          as _i4.Rx<_i19.UserModel?>);

  @override
  bool get isAdmin =>
      (super.noSuchMethod(Invocation.getter(#isAdmin), returnValue: false)
          as bool);

  @override
  _i4.RxList<_i19.UserModel> get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _FakeRxList_5<_i19.UserModel>(
              this,
              Invocation.getter(#users),
            ),
          )
          as _i4.RxList<_i19.UserModel>);

  @override
  _i4.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  _i4.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_4<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i4.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i14.Future<_i10.AuthService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i14.Future<_i10.AuthService>.value(
              _FakeAuthService_12(this, Invocation.method(#init, [])),
            ),
          )
          as _i14.Future<_i10.AuthService>);

  @override
  _i14.Future<_i19.UserModel?> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i14.Future<_i19.UserModel?>.value(),
          )
          as _i14.Future<_i19.UserModel?>);

  @override
  void logout() => super.noSuchMethod(
    Invocation.method(#logout, []),
    returnValueForMissingStub: null,
  );

  @override
  _i14.Future<void> addUser(_i19.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#addUser, [user]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  _i14.Future<void> updateUser(_i19.UserModel? updatedUser) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [updatedUser]),
            returnValue: _i14.Future<void>.value(),
            returnValueForMissingStub: _i14.Future<void>.value(),
          )
          as _i14.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
