// Mocks generated by Mockito 5.4.6 from annotations
// in fathiyah_store/test/services/sale_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i8;

import 'package:fathiyah_store/app/data/models/category_model.dart' as _i6;
import 'package:fathiyah_store/app/data/models/product_model.dart' as _i7;
import 'package:fathiyah_store/app/data/models/shift_model.dart' as _i10;
import 'package:fathiyah_store/app/data/models/stock_movement_model.dart'
    as _i12;
import 'package:fathiyah_store/app/data/models/user_model.dart' as _i9;
import 'package:fathiyah_store/app/data/services/auth_service.dart' as _i4;
import 'package:fathiyah_store/app/data/services/product_service.dart' as _i3;
import 'package:fathiyah_store/app/data/services/shift_service.dart' as _i5;
import 'package:fathiyah_store/app/data/services/stock_movement_service.dart'
    as _i11;
import 'package:get/get.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeRxList_0<E> extends _i1.SmartFake implements _i2.RxList<E> {
  _FakeRxList_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRxBool_1 extends _i1.SmartFake implements _i2.RxBool {
  _FakeRxBool_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInternalFinalCallback_2<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeProductService_3 extends _i1.SmartFake
    implements _i3.ProductService {
  _FakeProductService_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeRx_4<T> extends _i1.SmartFake implements _i2.Rx<T> {
  _FakeRx_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthService_5 extends _i1.SmartFake implements _i4.AuthService {
  _FakeAuthService_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeShiftService_6 extends _i1.SmartFake implements _i5.ShiftService {
  _FakeShiftService_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ProductService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProductService extends _i1.Mock implements _i3.ProductService {
  MockProductService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.RxList<_i6.CategoryModel> get categories =>
      (super.noSuchMethod(
            Invocation.getter(#categories),
            returnValue: _FakeRxList_0<_i6.CategoryModel>(
              this,
              Invocation.getter(#categories),
            ),
          )
          as _i2.RxList<_i6.CategoryModel>);

  @override
  _i2.RxList<_i7.ProductModel> get products =>
      (super.noSuchMethod(
            Invocation.getter(#products),
            returnValue: _FakeRxList_0<_i7.ProductModel>(
              this,
              Invocation.getter(#products),
            ),
          )
          as _i2.RxList<_i7.ProductModel>);

  @override
  _i2.RxBool get isLoading =>
      (super.noSuchMethod(
            Invocation.getter(#isLoading),
            returnValue: _FakeRxBool_1(this, Invocation.getter(#isLoading)),
          )
          as _i2.RxBool);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i8.Future<_i3.ProductService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<_i3.ProductService>.value(
              _FakeProductService_3(this, Invocation.method(#init, [])),
            ),
          )
          as _i8.Future<_i3.ProductService>);

  @override
  _i8.Future<void> addProduct(_i7.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#addProduct, [product]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateProduct(_i7.ProductModel? product) =>
      (super.noSuchMethod(
            Invocation.method(#updateProduct, [product]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> deleteProduct(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteProduct, [id]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i4.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Rx<_i9.UserModel?> get currentUser =>
      (super.noSuchMethod(
            Invocation.getter(#currentUser),
            returnValue: _FakeRx_4<_i9.UserModel?>(
              this,
              Invocation.getter(#currentUser),
            ),
          )
          as _i2.Rx<_i9.UserModel?>);

  @override
  bool get isAdmin =>
      (super.noSuchMethod(Invocation.getter(#isAdmin), returnValue: false)
          as bool);

  @override
  _i2.RxList<_i9.UserModel> get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _FakeRxList_0<_i9.UserModel>(
              this,
              Invocation.getter(#users),
            ),
          )
          as _i2.RxList<_i9.UserModel>);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i8.Future<_i4.AuthService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<_i4.AuthService>.value(
              _FakeAuthService_5(this, Invocation.method(#init, [])),
            ),
          )
          as _i8.Future<_i4.AuthService>);

  @override
  _i8.Future<_i9.UserModel?> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i8.Future<_i9.UserModel?>.value(),
          )
          as _i8.Future<_i9.UserModel?>);

  @override
  void logout() => super.noSuchMethod(
    Invocation.method(#logout, []),
    returnValueForMissingStub: null,
  );

  @override
  _i8.Future<void> addUser(_i9.UserModel? user) =>
      (super.noSuchMethod(
            Invocation.method(#addUser, [user]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> updateUser(_i9.UserModel? updatedUser) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [updatedUser]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ShiftService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShiftService extends _i1.Mock implements _i5.ShiftService {
  MockShiftService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Rx<_i10.ShiftModel?> get currentShift =>
      (super.noSuchMethod(
            Invocation.getter(#currentShift),
            returnValue: _FakeRx_4<_i10.ShiftModel?>(
              this,
              Invocation.getter(#currentShift),
            ),
          )
          as _i2.Rx<_i10.ShiftModel?>);

  @override
  _i2.RxList<_i10.ShiftModel> get shifts =>
      (super.noSuchMethod(
            Invocation.getter(#shifts),
            returnValue: _FakeRxList_0<_i10.ShiftModel>(
              this,
              Invocation.getter(#shifts),
            ),
          )
          as _i2.RxList<_i10.ShiftModel>);

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i8.Future<_i5.ShiftService> init() =>
      (super.noSuchMethod(
            Invocation.method(#init, []),
            returnValue: _i8.Future<_i5.ShiftService>.value(
              _FakeShiftService_6(this, Invocation.method(#init, [])),
            ),
          )
          as _i8.Future<_i5.ShiftService>);

  @override
  _i8.Future<void> openShift(double? startBalance) =>
      (super.noSuchMethod(
            Invocation.method(#openShift, [startBalance]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> closeShift(double? endBalance) =>
      (super.noSuchMethod(
            Invocation.method(#closeShift, [endBalance]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> recordCashSale(double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#recordCashSale, [amount]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Future<void> recordCashExpense(double? amount) =>
      (super.noSuchMethod(
            Invocation.method(#recordCashExpense, [amount]),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [StockMovementService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStockMovementService extends _i1.Mock
    implements _i11.StockMovementService {
  MockStockMovementService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.InternalFinalCallback<void> get onStart =>
      (super.noSuchMethod(
            Invocation.getter(#onStart),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onStart),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete =>
      (super.noSuchMethod(
            Invocation.getter(#onDelete),
            returnValue: _FakeInternalFinalCallback_2<void>(
              this,
              Invocation.getter(#onDelete),
            ),
          )
          as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized =>
      (super.noSuchMethod(Invocation.getter(#initialized), returnValue: false)
          as bool);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i8.Future<void> recordMovement({
    required String? productId,
    required String? productName,
    required int? quantity,
    required String? type,
    String? note = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recordMovement, [], {
              #productId: productId,
              #productName: productName,
              #quantity: quantity,
              #type: type,
              #note: note,
            }),
            returnValue: _i8.Future<void>.value(),
            returnValueForMissingStub: _i8.Future<void>.value(),
          )
          as _i8.Future<void>);

  @override
  _i8.Stream<List<_i12.StockMovementModel>> getMovementsForProduct(
    String? productId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovementsForProduct, [productId]),
            returnValue: _i8.Stream<List<_i12.StockMovementModel>>.empty(),
          )
          as _i8.Stream<List<_i12.StockMovementModel>>);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  void onReady() => super.noSuchMethod(
    Invocation.method(#onReady, []),
    returnValueForMissingStub: null,
  );

  @override
  void onClose() => super.noSuchMethod(
    Invocation.method(#onClose, []),
    returnValueForMissingStub: null,
  );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
    Invocation.method(#$configureLifeCycle, []),
    returnValueForMissingStub: null,
  );
}
